apiVersion: v2
name: medusa-store
description: A Helm chart for Medusa E-commerce Store
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: ~15.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~19.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
