apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "medusa-store.fullname" . }}-migration
  labels:
    {{- include "medusa-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["sh", "-c", "yarn medusa db:migrate"]
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable"
            - name: REDIS_URL
              value: "redis://{{ .Release.Name }}-redis-master:6379"
            - name: JWT_SECRET
              value: {{ .Values.backend.env.jwtSecret | quote }}
            - name: COOKIE_SECRET
              value: {{ .Values.backend.env.cookieSecret | quote }}
