apiVersion: v1
kind: Service
metadata:
  name: {{ include "medusa-store.fullname" . }}-storefront
  labels:
    {{- include "medusa-store.labels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
spec:
  type: {{ .Values.storefront.service.type }}
  ports:
    - port: {{ .Values.storefront.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "medusa-store.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
